### ISSUE TITLE
MD5 isn't the expected

### ISSUE THREAD

**Issue by rafaelmercuri** [overture-stack/score#152] opened 2019-04-28 18:08 UTC
Hi,
I've had some issues when i trying downloading some WGS.

Something like this:
"WARN: MD5 for /home/teste/228b7a2e-2263-519a-ac3f-4a44757387cd was d691490d36d57fc0f1e55f819d4a0eb2 but was expecting 9632a84b7822b571f9cfc3568c8a2707"

I used this code to downloaded the data:
bin/score-client download --manifest /home/teste/manifest.collaboratory.1556303837852.tsv --output-dir /home/teste/

**Comment by lindaxiang** [comment] 2019-05-24 20:04
Hi @rafaelmercuri 
Thank you for reporting the issue. 
I downloaded the same file from collaboratory by using the following command:
`score-client --profile collab download --object-id 228b7a2e-2263-519a-ac3f-4a44757387cd --output-dir .`
It went well without any issue.
I also tested the command you used above and it also works for me. 
I suspect it could be transient network issue which caused the corrupted bam file. 
Could you please try the downloading again and let us know if the issue still exists?
Good luck and sorry for the inconvenience!

**Comment by rosibaj** [comment] 2019-10-03 13:42
Closing issue as we were not able to reproduce the issue.

**Closed by rosibaj** 2019-10-03 13:42 UTC
Labels: invalid
